# Add versions
tap 'homebrew/versions'

# Install cask with versions and fonts
tap 'caskroom/cask'
brew 'caskroom/cask/brew-cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'

# Tap private repos
tap 'juanibiapina/zas'

# Install Apps
cask_args appdir: '/Applications'
cask '1password3'
cask 'appcleaner'
cask 'dropbox'
cask 'firefox'
cask 'iterm2'
cask 'java'
cask 'franz'
cask 'flux'
cask 'google-photos-backup'
cask 'dash'
cask 'skype'
cask 'spotify'
cask 'the-unarchiver'
cask 'transmission'
cask 'vlc'

# Install fonts
cask 'font-sauce-code-powerline'
cask 'font-iosevka'

# Install command line tools
brew 'ack'
brew 'bats'
brew 'coreutils'
brew 'ctags'
brew 'docker'
brew 'docker-compose'
brew 'docker-machine'
brew 'docker-swarm'
brew 'elasticsearch'
brew 'git'
brew 'heroku-toolbelt'
brew 'htop'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'mongodb'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'rbenv'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'zas'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
brew 'crystal-lang'

# Install neovim
tap 'neovim/neovim'
brew 'neovim', args: ['HEAD']
