# Taps
tap 'homebrew/services'
tap 'universal-ctags/universal-ctags'
tap 'neovim/neovim'

# --- COMMAND LINE TOOLS (Formulas) ---

# Utilities
brew 'ack'
brew 'awscli'
brew 'coreutils'
brew 'diff-so-fancy'
brew 'wget'
brew 'htop'
brew 'httpie'
brew 'hub'
brew 'gpg2'
brew 'jq'
brew 'yq'
brew 'tree'
brew 'ripgrep'
brew 'rlwrap'
brew 'readline'
brew 'parallel'
brew 'openssl'
brew 'shellcheck'
brew 'reattach-to-user-namespace'

# Coding & Languages
brew 'git'
brew 'node'
brew 'nvm'
brew 'yarn'
brew 'python3'
brew 'rbenv'
brew 'ruby-build'
brew 'tfenv'
brew 'stack'      # Haskell Stack
brew 'neovim'
brew 'editorconfig'

# Shell & Terminal
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
brew 'fzf'
brew 'tmux'
brew 'universal-ctags'

# Terminals & Editors
cask 'iterm2'

# Development
cask 'docker'
cask 'java'

# Browsers & Social
cask 'firefox'
cask 'slack'
cask 'zoom'

# System Tools
cask 'the-unarchiver'
cask 'karabiner-elements'
cask 'gswitch'
cask 'macs-fan-control'

# Fonts
cask 'font-iosevka-nerd-font'

# AI Stuff
cask 'cursor'
cask 'opencode'
