# vim: ft=zsh

zmodload zsh/zprof

export ZSH_HOME="$HOME/.dots/zsh"
export SHELL="$(which zsh)"
source $ZSH_HOME/init.zsh
export GPG_TTY=$(tty)

# opencode
export PATH=/Users/mboeira/.opencode/bin:$PATH
